name = "Creatify"
author = "IONNetwork, Juli0q"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d220c708293271e5c9ed49fc5da7536a389ebbe0a790bcc098575020a96b8c79"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
