name = "Creatify"
author = "IONNetwork, Juli0q"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c042ae83dc451203019c3fc0c61abff06faed612bdfff6b15d4404b94f833f78"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
