name = "Creatify"
author = "IONNetwork, Juli0q"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df0707500236ab9839773c48774c38e322eb6052ede96e53d07a72b468c59b7e"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
