name = "Creatify"
author = "IONNetwork, Juli0q"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b708fada46d477cb8edfa232cb33c8b4927f5cbffd0cdf29ca90ebf6f151178"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
