name = "Creatify"
author = "IONNetwork, Juli0q"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e7d80afb2fc75d3a4aeddd69f24450237e5e4096ef9cddfebfe8c36611bf5af"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
