name = "Creatify"
author = "IONNetwork, Juli0q"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "75e00a02066f160545298a7782058b5c7da9cd56746e7d76417bf1566ee98e10"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
