name = "Creatify"
author = "IONNetwork, Juli0q"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfad602d2dc2b331acb8c2adde84fd2a8e0e33af9351bb73c763ce364c3da6b2"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
